layout_spectrum: 0.46766141639091074
typography_spectrum: 0.9058618769049644
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.663140683202073
  lightness: 0.514011018909514
  saturation: 0.7388965727295727
  rhythmicContrast: 0.3569835366215557
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: David J Tyler
  email: david@dijitalmedia.co.uk
  url: www.dijitalmedia.co.uk
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/26c9ea33-2cc6-40de-bd8e-01db9ffd996d.png
name: Dijital Media Limited
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6cbbee39-0327-4a13-a3e5-30f535931517.png
title: Measured Marketing
description: Plus A Bit Of Know How..
purpose: []
