typography_spectrum: 0.8217509491369128
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2584409932605922
  lightness: 0.865217064274475
  saturation: 0.6966503008734435
  rhythmicContrast: 0.6575005818158388
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5931109609082341
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: David J Tyler
  email: david@dijitalmedia.co.uk
  url: www.dijitalmedia.co.uk
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/26c9ea33-2cc6-40de-bd8e-01db9ffd996d.png
name: Dijital Media Limited
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6cbbee39-0327-4a13-a3e5-30f535931517.png
title: Measured Marketing
description: Plus A Bit Of Know How..
purpose: []
